apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: node-print
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: node-print
    spec:
      completions: 10
      parallelism: 5
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            name: node-print
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
status: {}
