apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ClusterRole
subjects:
- kind: ServiceAccount
  name: alisher
  namespace: alisher
